[buildPlans.ryans-iosevka]
family = "Ryan's Iosevka"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.ryans-iosevka.variants]
  inherits = "ss05"

[buildPlans.ryans-iosevka.widths.normal]
shape = 600
menu = 5
css = "normal"
