name: build
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: install fonts stuff
        run: |
          mkdir work
          curl -fsSL 'https://github.com/fontforge/fontforge/releases/download/20220308/FontForge-2022-03-08-582bd41-x86_64.AppImage' > work/fontforge
          chmod +x work/fontforge
          sudo apt-get update
          sudo apt-get install ttfautohint

      - name: build
        run: deno run -A mod.ts

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ryans-iosevka.zip
          path: work/ryans-iosevka.zip
